version: '3'
services:
  ais-api:
    build: .
    image: kenguru33/rs-position-tracker
    networks: 
      - aisnet-backend
    ports: 
      - 3000:3000  
    environment:
      - ENABLE_API=true
      - ENABLE_AIS_FETCHER=true
      - AIS_DATA_URL=https://ais.rs.no/aktive_pos.json
      - DB_URI=mongodb://mongodb-service/rsbase
      - DB_HOST=mongodb-service/rsbase
      - DB_USER=""
      - DB_PASSWORD=""
    volumes:
      - ./src:/app/src
    restart: on-failure
    command: [ "node_modules/nodemon/bin/nodemon.js", "src/app.js"]
  mongodb-service:
    image: bitnami/mongodb
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2
      - MONGODB_DATABASE=rsbase
    networks: 
      - aisnet-backend
    ports: 
      - 27017:27017
networks:
  aisnet-backend:

 